import { Show } from './types';

// Mock data untuk testing saat API limit tercapai
export const mockMovies: Show[] = [
  {
    id: 'tt0111161',
    title: 'The Shawshank Redemption',
    overview: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    releaseYear: 1994,
    originalTitle: 'The Shawshank Redemption',
    genres: [{ id: 'drama', name: 'Drama' }],
    rating: 9.3,
    imageSet: {
      verticalPoster: {
        w240: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
        w360: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
        w480: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
        w600: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
        w720: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
      },
      horizontalPoster: {
        w360: 'https://image.tmdb.org/t/p/w1280/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
        w480: 'https://image.tmdb.org/t/p/w1280/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
        w720: 'https://image.tmdb.org/t/p/w1280/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
        w1080: 'https://image.tmdb.org/t/p/w1280/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
        w1440: 'https://image.tmdb.org/t/p/w1280/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
      },
    },
    showType: 'movie',
  },
  {
    id: 'tt0068646',
    title: 'The Godfather',
    overview: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    releaseYear: 1972,
    originalTitle: 'The Godfather',
    genres: [{ id: 'crime', name: 'Crime' }, { id: 'drama', name: 'Drama' }],
    rating: 9.2,
    imageSet: {
      verticalPoster: {
        w240: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
        w360: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
        w480: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
        w600: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
        w720: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
      },
      horizontalPoster: {
        w360: 'https://image.tmdb.org/t/p/w1280/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
        w480: 'https://image.tmdb.org/t/p/w1280/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
        w720: 'https://image.tmdb.org/t/p/w1280/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
        w1080: 'https://image.tmdb.org/t/p/w1280/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
        w1440: 'https://image.tmdb.org/t/p/w1280/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
      },
    },
    showType: 'movie',
  },
  {
    id: 'tt0468569',
    title: 'The Dark Knight',
    overview: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests.',
    releaseYear: 2008,
    originalTitle: 'The Dark Knight',
    genres: [{ id: 'action', name: 'Action' }, { id: 'crime', name: 'Crime' }],
    rating: 9.0,
    imageSet: {
      verticalPoster: {
        w240: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        w360: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        w480: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        w600: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        w720: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
      },
      horizontalPoster: {
        w360: 'https://image.tmdb.org/t/p/w1280/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg',
        w480: 'https://image.tmdb.org/t/p/w1280/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg',
        w720: 'https://image.tmdb.org/t/p/w1280/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg',
        w1080: 'https://image.tmdb.org/t/p/w1280/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg',
        w1440: 'https://image.tmdb.org/t/p/w1280/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg',
      },
    },
    showType: 'movie',
  },
  {
    id: 'tt13320622',
    title: 'Squid Game',
    overview: 'Hundreds of cash-strapped players accept a strange invitation to compete in children\'s games. Inside, a tempting prize awaits with deadly high stakes.',
    firstAirYear: 2021,
    originalTitle: 'Squid Game',
    genres: [{ id: 'drama', name: 'Drama' }, { id: 'thriller', name: 'Thriller' }],
    rating: 8.0,
    seasonCount: 2,
    episodeCount: 17,
    imageSet: {
      verticalPoster: {
        w240: 'https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg',
        w360: 'https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg',
        w480: 'https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg',
        w600: 'https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg',
        w720: 'https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg',
      },
      horizontalPoster: {
        w360: 'https://image.tmdb.org/t/p/w1280/9RBaCFfg3TY5kexLjhauKepWs7k.jpg',
        w480: 'https://image.tmdb.org/t/p/w1280/9RBaCFfg3TY5kexLjhauKepWs7k.jpg',
        w720: 'https://image.tmdb.org/t/p/w1280/9RBaCFfg3TY5kexLjhauKepWs7k.jpg',
        w1080: 'https://image.tmdb.org/t/p/w1280/9RBaCFfg3TY5kexLjhauKepWs7k.jpg',
        w1440: 'https://image.tmdb.org/t/p/w1280/9RBaCFfg3TY5kexLjhauKepWs7k.jpg',
      },
    },
    showType: 'series',
  },
  {
    id: 'tt0816692',
    title: 'Interstellar',
    overview: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    releaseYear: 2014,
    originalTitle: 'Interstellar',
    genres: [{ id: 'scifi', name: 'Science Fiction' }, { id: 'drama', name: 'Drama' }],
    rating: 8.6,
    imageSet: {
      verticalPoster: {
        w240: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        w360: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        w480: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        w600: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        w720: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
      },
      horizontalPoster: {
        w360: 'https://image.tmdb.org/t/p/w1280/xu9zaAevzQ5nnrsXN6JcahLnG4i.jpg',
        w480: 'https://image.tmdb.org/t/p/w1280/xu9zaAevzQ5nnrsXN6JcahLnG4i.jpg',
        w720: 'https://image.tmdb.org/t/p/w1280/xu9zaAevzQ5nnrsXN6JcahLnG4i.jpg',
        w1080: 'https://image.tmdb.org/t/p/w1280/xu9zaAevzQ5nnrsXN6JcahLnG4i.jpg',
        w1440: 'https://image.tmdb.org/t/p/w1280/xu9zaAevzQ5nnrsXN6JcahLnG4i.jpg',
      },
    },
    showType: 'movie',
  },
  {
    id: 'tt0109830',
    title: 'Forrest Gump',
    overview: 'The presidencies of Kennedy and Johnson, the Vietnam War, and other historical events unfold from the perspective of an Alabama man.',
    releaseYear: 1994,
    originalTitle: 'Forrest Gump',
    genres: [{ id: 'drama', name: 'Drama' }, { id: 'romance', name: 'Romance' }],
    rating: 8.8,
    imageSet: {
      verticalPoster: {
        w240: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
        w360: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
        w480: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
        w600: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
        w720: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
      },
      horizontalPoster: {
        w360: 'https://image.tmdb.org/t/p/w1280/vFpEe35dY7iW6H4kh8rPmkLWy3G.jpg',
        w480: 'https://image.tmdb.org/t/p/w1280/vFpEe35dY7iW6H4kh8rPmkLWy3G.jpg',
        w720: 'https://image.tmdb.org/t/p/w1280/vFpEe35dY7iW6H4kh8rPmkLWy3G.jpg',
        w1080: 'https://image.tmdb.org/t/p/w1280/vFpEe35dY7iW6H4kh8rPmkLWy3G.jpg',
        w1440: 'https://image.tmdb.org/t/p/w1280/vFpEe35dY7iW6H4kh8rPmkLWy3G.jpg',
      },
    },
    showType: 'movie',
  },
];

export const mockSeries: Show[] = [
  {
    id: 'tt0903747',
    title: 'Breaking Bad',
    overview: 'A high school chemistry teacher turned methamphetamine producer partners with a former student.',
    firstAirYear: 2008,
    lastAirYear: 2013,
    originalTitle: 'Breaking Bad',
    genres: [{ id: 'drama', name: 'Drama' }, { id: 'crime', name: 'Crime' }],
    rating: 9.5,
    seasonCount: 5,
    episodeCount: 62,
    imageSet: {
      verticalPoster: {
        w240: 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
        w360: 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
        w480: 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
        w600: 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
        w720: 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
      },
      horizontalPoster: {
        w360: 'https://image.tmdb.org/t/p/w1280/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
        w480: 'https://image.tmdb.org/t/p/w1280/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
        w720: 'https://image.tmdb.org/t/p/w1280/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
        w1080: 'https://image.tmdb.org/t/p/w1280/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
        w1440: 'https://image.tmdb.org/t/p/w1280/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
      },
    },
    showType: 'series',
  },
  {
    id: 'tt0944947',
    title: 'Game of Thrones',
    overview: 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns.',
    firstAirYear: 2011,
    lastAirYear: 2019,
    originalTitle: 'Game of Thrones',
    genres: [{ id: 'drama', name: 'Drama' }, { id: 'fantasy', name: 'Fantasy' }],
    rating: 9.3,
    seasonCount: 8,
    episodeCount: 73,
    imageSet: {
      verticalPoster: {
        w240: 'https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
        w360: 'https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
        w480: 'https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
        w600: 'https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
        w720: 'https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
      },
      horizontalPoster: {
        w360: 'https://image.tmdb.org/t/p/w1280/suopoADq0k8YZr4dQXcU6pToj6s.jpg',
        w480: 'https://image.tmdb.org/t/p/w1280/suopoADq0k8YZr4dQXcU6pToj6s.jpg',
        w720: 'https://image.tmdb.org/t/p/w1280/suopoADq0k8YZr4dQXcU6pToj6s.jpg',
        w1080: 'https://image.tmdb.org/t/p/w1280/suopoADq0k8YZr4dQXcU6pToj6s.jpg',
        w1440: 'https://image.tmdb.org/t/p/w1280/suopoADq0k8YZr4dQXcU6pToj6s.jpg',
      },
    },
    showType: 'series',
  },
  {
    id: 'tt0386676',
    title: 'The Office',
    overview: 'A mockumentary on a group of typical office workers, where the workday consists of ego clashes and inappropriate behavior.',
    firstAirYear: 2005,
    lastAirYear: 2013,
    originalTitle: 'The Office',
    genres: [{ id: 'comedy', name: 'Comedy' }],
    rating: 9.0,
    seasonCount: 9,
    episodeCount: 201,
    imageSet: {
      verticalPoster: {
        w240: 'https://image.tmdb.org/t/p/w500/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg',
        w360: 'https://image.tmdb.org/t/p/w500/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg',
        w480: 'https://image.tmdb.org/t/p/w500/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg',
        w600: 'https://image.tmdb.org/t/p/w500/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg',
        w720: 'https://image.tmdb.org/t/p/w500/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg',
      },
      horizontalPoster: {
        w360: 'https://image.tmdb.org/t/p/w1280/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg',
        w480: 'https://image.tmdb.org/t/p/w1280/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg',
        w720: 'https://image.tmdb.org/t/p/w1280/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg',
        w1080: 'https://image.tmdb.org/t/p/w1280/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg',
        w1440: 'https://image.tmdb.org/t/p/w1280/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg',
      },
    },
    showType: 'series',
  },
];

